language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# install pip packages
install:
  - "pip install -r requirements.txt"
env:
  - DRESS_CONFIGURATION=testing
script:
  - python -m unittest discover tests "*_tests.py"
