"""empty message

Revision ID: 504b1e7990c9
Revises: 
Create Date: 2017-12-31 15:04:53.214537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504b1e7990c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=32), nullable=True),
    sa.Column('pwd', sa.String(length=32), nullable=True),
    sa.Column('db_pwd', sa.String(length=32), nullable=True),
    sa.Column('memo', sa.String(length=32), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host')
    op.drop_table('status')
    # ### end Alembic commands ###
