"""empty message

Revision ID: e6cdbd3e90c1
Revises: 3477020cccce
Create Date: 2018-02-10 12:43:11.746157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cdbd3e90c1'
down_revision = '3477020cccce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=True),
    sa.Column('custom_data', sa.JSON(), nullable=True),
    sa.Column('logtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasklog')
    # ### end Alembic commands ###
